### ISSUE TITLE
[Bug]: VSCode 1.94 (Insiders) is incompatible

### ISSUE THREAD

**Issue by RoyalFoxy** [illixion/vscode-vibrancy-continued#162]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Extension doesn't activate.

### Expected Behavior

Extension should activate.

### Steps To Reproduce

1. Install latest vscode-insiders version
2. Install vibrancy-continued
3. Open logs and check extension host
4. There should be following error or something similiar

```
2024-09-12 06:47:11.816 [info] ExtensionService#_doActivateExtension illixion.vscode-vibrancy-continued, startup: false, activationEvent: '*'
2024-09-12 06:47:11.831 [error] Activating extension illixion.vscode-vibrancy-continued failed due to an error:
2024-09-12 06:47:11.831 [error] TypeError: Cannot read properties of undefined (reading 'filename')
    at activate (/Users/royalfoxy/.vscode-insiders/extensions/illixion.vscode-vibrancy-continued-1.1.37/extension/index.js:244:42)
    at Function.kb (file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:116:15217)
    at Function.jb (file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:116:14924)
    at file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:116:13082
    at a0.n (file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:112:4450)
    at a0.m (file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:112:4413)
    at a0.l (file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:112:3869)
```

### Environment

```markdown
- OS: MacOS 15
- VSCode: 1.94.0
- Extension: 1.1.37
- Theme: Catppuccin Mocha
```

### Anything else?

I'm sad vscode broke it with the latest update :(

**Comment by illixion** [comment]
Thanks for discovering and posting about this, 1.94 changes some of the variables and file names we use, and workbench.html now uses ESM for JS. I've made some initial fixes in [this commit](https://github.com/illixion/vscode-vibrancy-continued/commit/6107157ece669c0407325c0fe9e59f620c9080cb) and will look into a full fix over the weekend.

**Comment by RoyalFoxy** [comment]
Thank you a ton for your quick work Illixion, you're the best <3

**Comment by illixion** [comment]
I've fixed ESM-related issues, but the vibrancy effect still doesn't seem to activate even though there are no errors, I couldn't find any leads so far but will continue looking. My changes are in [feature/esm-refactor](https://github.com/illixion/vscode-vibrancy-continued/tree/feature/esm-refactor) branch if anyone wants to help, to debug simply clone the branch and press F5 while editing `extension/index.js`.

**Comment by RoyalFoxy** [comment]
Thanks a lot for your help! I'll try and look into it the next couple days if I find time after my day job.

**Comment by illixion** [comment]
I've found what was causing this, and version **1.1.38** should now work on VSCode 1.94, though it is a pre-release version so make sure to opt into it using the cog menu in Extensions. Feel free to try it out and let me know if it works properly for you.

**Comment by RoyalFoxy** [comment]
It works flawlessly again. Thank you so very much Illixion ❤️
