### ISSUE TITLE
Vibrancy on arm64 Windows causes Code to crash on start

### ISSUE THREAD

**Issue by illixion** [illixion/vscode-vibrancy-continued#9]
```
[main 2022-08-27T17:51:51.106Z] Error: \\?\c:\Users\User\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vscode-vibrancy-runtime-v6\vibrancy.node is not a valid Win32 application.
\\?\c:\Users\User\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vscode-vibrancy-runtime-v6\vibrancy.node
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:5:1812)
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1246:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:5:1812)
    at Module.load (node:internal/modules/cjs/loader:1035:32)
    at Module._load (node:internal/modules/cjs/loader:876:12)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13343)
    at Module.require (node:internal/modules/cjs/loader:1059:19)
    at p (C:\Users\User\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:4:699)
    at Object.<anonymous> (c:\Users\User\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vscode-vibrancy-runtime-v6\vibrancy.js:1:77)
    at Module.u._compile (C:\Users\User\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:4:1313)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1216:10)
    at Module.load (node:internal/modules/cjs/loader:1035:32)
    at Module._load (node:internal/modules/cjs/loader:876:12)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13343)
    at Module.require (node:internal/modules/cjs/loader:1059:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at App.<anonymous> (c:\Users\User\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vscode-vibrancy-runtime-v6\index.js:53:20)
    at App.emit (node:events:390:28)
    at BrowserWindow.n._init (node:electron/js2c/browser_init:37:1043)
    at new H (C:\Users\User\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:76:45915)
    at C._createInstance (C:\Users\User\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:31:1346)
    at C.createInstance (C:\Users\User\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:31:779)
    at ht.openInBrowserWindow (C:\Users\User\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:77:52672)
    at ht.doOpenEmpty (C:\Users\User\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:77:41118)
    at C:\Users\User\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:77:40041
    at Array.forEach (<anonymous>)
    at ht.doOpen (C:\Users\User\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:77:39934)
    at ht.open (C:\Users\User\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:77:35543)
    at Ct.openFirstWindow (C:\Users\User\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:77:75392)
    at C:\Users\User\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:77:64658
    at C.invokeFunction (C:\Users\User\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:31:325)
    at Ct.startup (C:\Users\User\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:77:64634)
    at async Ce.startup (C:\Users\User\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:79:5801)
```

**Comment by illixion** [comment]
Partial fix added in v1.1.24 to prevent installation on ARM Windows. Possible workaround would be to use the x64 version of VSCode through a compatibility layer, though this is suboptimal. Proper fix would likely be to recompile the node modules and add logic to use the correct ones depending on the OS and CPU architecture.

**Comment by adamprogramer** [comment]
VS Code don't want to be **resizable**
